Add routes
gene83/ng-rolodex pull request #3
Opened 2019-02-21 03:07 UTC by gene83

2019-02-21 23:39 UTC, melsoriano approved these changes
LGTM ✅

2019-02-21 23:43 UTC, taesup requested changes

2019-02-21 23:43 UTC, taesup commented on server/routes/api/contacts/index.js
> +      const filteredContacts = contacts.filter(contact => {
You should try to use the DB to filter the contacts, it'll be faster.

2019-02-21 23:43 UTC, taesup commented on server/routes/api/contacts/index.js
> +      res.status(200);
You don't need to do a status 200. `res.json` will set it to 200 for you.

2019-02-21 23:43 UTC, taesup commented on server/routes/api/index.js
> +        .then(resUser => {
You should return the dbUser, then the `.then` and the `.catch` here can be part of the upper promise chain.

2019-02-22 23:40 UTC, taesup approved these changes

2019-02-22 23:42 UTC, merged